name: workflow
on:
  push:
    branch:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  
  e2e-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npm install --save-dev cypress  

      - name: Open Front-end folder
        run: cd Front-End/app-frontend
 
      - name: Run Cypress tests
        run: npx cypress run
